# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'email2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *



class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(549, 415)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setFocusPolicy(QtCore.Qt.TabFocus)
        Form.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.cancel = QtWidgets.QPushButton(Form)
        self.cancel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancel.setObjectName("cancel")
        self.gridLayout.addWidget(self.cancel, 6, 1, 1, 1)
        self.subjekt = QtWidgets.QLineEdit(Form)
        self.subjekt.setText("")
        self.subjekt.setClearButtonEnabled(True)
        self.subjekt.setProperty("Subjekt", "")
        self.subjekt.setObjectName("subjekt")
        self.gridLayout.addWidget(self.subjekt, 3, 0, 1, 3)
        self.send = QtWidgets.QPushButton(Form)
        self.send.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.send.setFocusPolicy(QtCore.Qt.TabFocus)
        self.send.setAcceptDrops(False)
        self.send.setAutoDefault(False)
        self.send.setDefault(True)
        self.send.setFlat(False)
        self.send.setObjectName("send")
        self.gridLayout.addWidget(self.send, 6, 2, 1, 1)
        self.nach_email = QtWidgets.QLineEdit(Form)
        self.nach_email.setText("")
        self.nach_email.setClearButtonEnabled(True)
        self.nach_email.setObjectName("nach_email")
        self.gridLayout.addWidget(self.nach_email, 2, 0, 1, 3)
        self.email_text = QtWidgets.QTextEdit(Form)
        self.email_text.setObjectName("email_text")
        self.gridLayout.addWidget(self.email_text, 5, 0, 1, 3)
        self.clear = QtWidgets.QPushButton(Form)
        self.clear.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.clear.setObjectName("clear")
        self.gridLayout.addWidget(self.clear, 6, 0, 1, 1)
        self.psw = QtWidgets.QLineEdit(Form)
        self.psw.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.psw.setText("")
        self.psw.setEchoMode(QtWidgets.QLineEdit.Password)
        self.psw.setClearButtonEnabled(True)
        self.psw.setObjectName("psw")
        self.gridLayout.addWidget(self.psw, 1, 0, 1, 1)
        self.von_email = QtWidgets.QLineEdit(Form)
        self.von_email.setText("")
        self.von_email.setClearButtonEnabled(True)
        self.von_email.setObjectName("von_email")
        self.gridLayout.addWidget(self.von_email, 0, 0, 1, 3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.cancel.clicked.connect(QCoreApplication.instance().quit)
        self.clear.clicked.connect(self.temizle)
        self.send.clicked.connect(self.mail_gonder)
        
        
    def temizle(self):
        self.email_text.clear()

    def mail_gonder(self):

        mesaj = MIMEMultipart()  # Mail yapımızı oluşturuyoruz.

        mesaj["From"] = self.von_email.text()
        print(self.von_email.text())  # Kimden Göndereceğimiz

        mesaj["To"] = self.nach_email.text()  # Kime Göndereceğimiz
        print(self.nach_email.text())
        mesaj["Subject"] = self.subjekt.text()  # Mailimizin Konusu
        print(self.subjekt.text())

        # Mailimizin İçeriği
        yazi = self.email_text.toPlainText()
       
        # Mailimizin gövdesini bu sınıftan oluşturuyoruz.
        mesaj_govdesi = MIMEText(yazi, "plain")

        # Mailimizin gövdesini mail yapımıza ekliyoruz.
        mesaj.attach(mesaj_govdesi)

        try:
            # SMTP objemizi oluşturuyoruz ve gmail smtp server'ına bağlanıyoruz.
            mail = smtplib.SMTP("smtp.gmail.com", 587)

            mail.ehlo()  # SMTP serverına kendimizi tanıtıyoruz.

            mail.starttls()  # Adresimizin ve Parolamızın şifrelenmesi için gerekli

            # SMTP server'ına giriş yapıyoruz. Kendi mail adresimizi ve parolamızı yapıyoruz.
            mail.login(f"{self.von_email.text()}", f"{self.psw.text()}")

            # Mailimizi gönderiyoruz.
            mail.sendmail(mesaj["From"], mesaj["To"], mesaj.as_string())
            print("Mail başarıyla gönderildi....")
            
            mail.close()  # Smtp serverımızın bağlantısını koparıyoz.
            
        except:
            # Herhangi bir bağlanma sorunu veya mail gönderme sorunu olursa
            sys.stderr.write("Mail göndermesi başarısız oldu...")
            sys.stderr.flush()
        sys.exit()
        
           
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "GMAIL"))
        self.cancel.setText(_translate("Form", "Iptal"))
        self.subjekt.setPlaceholderText(_translate("Form", "Konu"))
        self.send.setText(_translate("Form", "Gönder"))
        self.nach_email.setPlaceholderText(_translate("Form", "email"))
        self.clear.setText(_translate("Form", "Temizle"))
        self.psw.setPlaceholderText(_translate("Form", "GMail sifreniz"))
        self.von_email.setPlaceholderText(_translate("Form", "GMail adresiniz"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
